# Generated by Django 3.0 on 2020-07-03 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wallet',
            old_name='amount',
            new_name='balance',
        ),
    ]
